### ISSUE TITLE
I can't find .annot file in NAMIC interlinkage you provide

### ISSUE THREAD

**Issue by ruoyu-z** [Shape-Lab/SPHARM-Net#1]
just .label file

**Comment by ruoyu-z** [comment]
I am a novice. In Mindboggle-101, I just find .vtk surfcare file. And I didn't find the result of freesurfer processing. Could you tell me if I need to use freesurfer to handle it?

**Comment by ilwoolyu** [comment]
Thank you for reaching out to us. Please note that we are not the owners of the datasets you are referring to, so we encourage you to direct any questions you have to the owners. You may also find some helpful information in the FreeSurfer package.
- If you're looking to convert labels to annot, we recommend checking out the following resource: https://surfer.nmr.mgh.harvard.edu/fswiki/mris_label2annot.
- While our tool supports several formats besides FreeSurfer, if you're new to surface data processing, we recommend using the FreeSurfer data structure. Additionally, the Mindboggle-101 dataset contains FreeSurfer processing with manual labels in annot format, which may be helpful for your purposes.

**Comment by ruoyu-z** [comment]
Thanks for your reply. I have found manual labels in annot format in Mindboggle-101 dataset. And I am trying to runing train.
