### ISSUE TITLE
May I ask where you obtained your icosphere .vtk file?

### ISSUE THREAD

**Issue by ruoyu-z** [Shape-Lab/SPHARM-Net#2]
Dear Shape-Lab,

I want to observe the effect of SPHARM on spheres of other scales(like ico5 , ico7). I found some. vtk files on Github, but they seem to be different from the ico6.vtk you provided. I think I may have made a mistake. 
So I wonder where you obtained your ico6.vtk, and I would like to obtain some different scales of ico.vtk.

Looking forward to your reply

**Comment by ilwoolyu** [comment]
Thanks for reaching out to us. Our method is independent of a specific tessellation because it does not rely on neighborhood information. Any spherical tessellation should work fine, which means that you can use any mesh files you have. All you need is to just supply your mesh file to `--sphere` in `prep.py` and `train.py`.

**Comment by ruoyu-z** [comment]
Thank you for your timely reply.

Could you tell me where I can get icosphere mesh in vtk format? 

I am not very familiar with this format,  actually，the mesh format I often use is the _.surf.gii_ . I can obtain ico6.vtk through the command line you provided. How can I obtain icosphere mesh of other scales?

**Comment by ruoyu-z** [comment]
Dear ilwoolyu,

I noticed that the ico6 you provided is a spherical mesh with a radius of 1, but the icospheres I found in your repositories [https://github.com/ilwoolyu/HSD/tree/master/script/sphere] are all mesh with a radius of 100. 

I also try to use https://github.com/ilwoolyu/SphericalLabeling/blob/master/gen_ico.py to generate icosahedral mesh files, but I cannot access the URL in the code.

I'm not sure if using mesh with different radius will affect the resultsof SPHARM. I **would greatly appreciate it if you could provide me with other sizes of icosphere** (such as ico3. vtk to ico7.vtk).

Looking forward to your reply

**Comment by se122811** [comment]
You can normalize the mesh with a radius of 100 by dividing it to 100. For convenience, I share the icosphere(the level of 0 to 7).
link: https://drive.google.com/drive/folders/1soji525WMtsNID4X8iKHkbL2ud9-QSOj?usp=sharing

**Comment by ruoyu-z** [comment]
This is very helpful for my study. Thank you very much.
