### ISSUE TITLE
Training and prediction on non-brain data

### ISSUE THREAD

**Issue by schbalint98** [Shape-Lab/SPHARM-Net#3]
Hi!

I have biological (non-brain) images in .tif stacks format that I would like to use as input to SPHARM-NET. Is there any way to circumvent the freesurfer format? So far I have only been able to train and make predictions on brain images.

Thanks,
Bálint

**Comment by ilwoolyu** [comment]
Thank you for reaching out to us. SPHARM-Net works for any spherical data though you may need to slightly modify `scripts/prep.py`. You first need to build a spherical mapping of your images.
